const AllCategoriesProducts = [
    {
        id: 1,
        img: "./img/products/products-crocs-1.jpg",
        brand: 'Crocks',
        title: 'Green Zing 3 RR',
        price: '120',
    },
    {
        id: 2,
        img: "./img/products/products-misbhv-1.jpg",
        brand: 'MISBHV',
        title: 'MISBHV / Sleeps',
        price: '123',
    },
    {
        id: 3,
        img: "./img/products/products-nmd-1.jpg",
        brand: 'Adidas',
        title: 'NMD Type 4/CAMO',
        price: '158',
    },
    {
        id: 4,
        img: "./img/products/products-raf-1.jpg",
        brand: 'Raf simons',
        title: 'Runner / Black Tron',
        price: '192',
    },
    {
        id: 5,
        img: "./img/products/products-runner-1.jpg",
        brand: 'Adidas',
        title: 'Big spuns T3T',
        price: '148',
    },
    {
        id: 6,
        img: "./img/products/products-slides-1.jpg",
        brand: 'Adidas',
        title: 'Orange sleepers/3',
        price: '210',
    },
    {
        id: 7,
        img: "./img/products/products-vmv-1.jpg",
        brand: 'Nike',
        title: 'Brown ice cream / 3',
        price: '173',
    },
    {
        id: 9,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },
    {
        id: 10,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },
    {
        id: 11,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },
    {
        id: 12,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },
    {
        id: 13,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },{
        id: 14,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },{
        id: 15,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },{
        id: 16,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },{
        id: 17,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },
    {
        id: 18,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },
    {
        id: 19,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },
    {
        id: 20,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },
    {
        id: 21,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },{
        id: 22,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },
    {
        id: 23,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },
    {
        id: 24,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    },
    {
        id: 25,
        img: "./img/products/products-continental-1.jpg",
        brand: 'Adidas',
        title: 'crazy mode v3',
        price: '212',
    }

]

export default AllCategoriesProducts